services:
#mssql docker
  ebiblioteka-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - ebibliotekanet

  ebiblioteka-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eBiblioteka=Server=ebiblioteka-sql,1433;Database=eBiblioteka;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5214:5214
    networks:
      - ebibliotekanet
    links:
      - ebiblioteka-sql
    depends_on:
      - ebiblioteka-sql
      
networks:
  ebibliotekanet:
    driver: bridge      