services:
#mssql docker
  ebiblioteka-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - ebibliotekanet

  ebiblioteka-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eBiblioteka=Server=${DB_SERVER},1433;Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD}; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=erestorante-rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
      - RABBITMQ_PORT=5672
    ports:
      - 5214:5214
    networks:
      - ebibliotekanet
    links:
      - ebiblioteka-sql
    depends_on:
      - ebiblioteka-sql
      - ebiblioteka-rabbitmq

#rabbitMQ
  ebiblioteka-rabbitmq:
    image: rabbitmq:management
    hostname: ebiblioteka-rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672  
      - 15672:15672
    expose:
      - 5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME} 
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - ebibliotekanet
    volumes:
      - ./docker_data/rabbitmq_data:/var/lib/rabbitmq
      - ./docker_data/rabbitmq_logs:/var/log/rabbitmq

#MailingService

  ebiblioteka-mailingservice:
    restart: unless-stopped
    container_name: ebiblioteka-mailingservice
    hostname: ebiblioteka-mailingservice
    image: subscriber-email-consumer:latest
    build: 
      context: .
      dockerfile: SubscriberDockerfile
    environment:
      - RABBITMQ_HOST=ebiblioteka-rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
      - RABBITMQ_PORT=5672
      - FromEmail=${FROM_EMAIL}
      - SmtpPass=${SMTP_PASS}
      - SmtpUser=${SMTP_USER}
    depends_on:
      - ebiblioteka-rabbitmq
      - ebiblioteka-api
      - ebiblioteka-sql 
    networks:
      - ebibliotekanet

networks:
  ebibliotekanet:
    driver: bridge      